name: tile-mate
channels:
 - conda-forge
dependencies:
 - python>=3.9
 - jupyter
 - ipykernel
 - rasterio
 - shapely
 - numpy
 - matplotlib
 - fiona
 - geopandas
 - gdal
 - boto3
 - pip
 - dem_stitcher>=2.5.4
 - pandas
 - pandera
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - pytest
 - pytest-cov
 - ruff
